-- Add SEO description column to aircraft_reference_specs
-- Used on model pages for SEO/GEO-optimized content
ALTER TABLE aircraft_reference_specs
ADD COLUMN IF NOT EXISTS seo_description TEXT;

COMMENT ON COLUMN aircraft_reference_specs.seo_description IS 'SEO/GEO-optimized model description (2-4 sentences, generated by Claude Haiku)';
